### ISSUE TITLE
cannot run home bridge

### ISSUE THREAD

**Issue by ciapamusche** [dotsam/homebridge-milight#11]
This is my error message

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

any ideas?

**Comment by dotsam** [comment]
Looks like you already have something running on port 51826 (maybe another instance of Homebridge that you didn't stop?), but regardless, it's not getting to the point yet of loading this plugin, so as suggested in the Homebridge readme (https://github.com/nfarina/homebridge#community) you should open an issue over there or join their Slack channel for more help.

**Comment by ciapamusche** [comment]
already changed the port.
The program runs . iPhone can see the home bridge but when i insert the pin code in my phone after a while it says impossible to connect
