### ISSUE TITLE
Config.json error

### ISSUE THREAD

**Issue by fjh40** [dotsam/homebridge-milight#40]
Hello, i'm Felix and completely new to using Ubuntu.

I've tried to install homebridge and get that to work with MiLight, only i can't seem to get the config.json file right.

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/4/2017, 2:35:19 PM] Loaded plugin: homebridge-milight
[11/4/2017, 2:35:19 PM] Registering platform 'homebridge-milight.MiLight'
[11/4/2017, 2:35:19 PM] ---
[11/4/2017, 2:35:19 PM] There was a problem reading your config.json file.
[11/4/2017, 2:35:19 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[11/4/2017, 2:35:19 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:206
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 11
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:200:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

Here is my config.json file.

"platforms": [
        {
            "platform":"MiLight",
            "name":"MiLight",
            "bridges": [
              {
                "ip_address": "192.168.1.12,
                "type": "rgbw",
                "zones": ["1","2","3","4"],
                "repeat": 1,
                "delay": 100
              },
              {
                "ip_address": "10.0.1.4",
                "type": "white",
                "zones": ["1","2","3","4"],
                "repeat": 1
              }]
        }
]

I do not understand what i'm doing wrong and how it can be fixed. I've searched the entire web but haven't gotten an single answer.

Thanks for your time!

**Comment by dotsam** [comment]
Hi Felix,

As the error mentions, your first step is to check your `config.json` for errors at somewhere like http://jsonlint.com/. If what you included in your message is your complete `config.json` file, then it's missing a bit of information. You should look at the sample homebridge config https://github.com/nfarina/homebridge/blob/master/config-sample.json to see what else is needed, and where the "platform" key you have above should fit in. In addition to that, I see you're also missing a closing quote at the end of your first `ip_address` key.

Putting it all together, a potentially working configuration would look something like this:
```json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "MiLight",
		"name": "MiLight",
		"bridges": [{
				"ip_address": "192.168.1.12",
				"type": "rgbw",
				"zones": ["1", "2", "3", "4"],
				"repeat": 1,
				"delay": 100
			},
			{
				"ip_address": "10.0.1.4",
				"type": "white",
				"zones": ["1", "2", "3", "4"],
				"repeat": 1
			}
		]
	}]
}
```
