### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by tystik4056** [dotsam/homebridge-milight#43]
I updated to the latest version on homebridge (0.4.32) and it seems to have broken my milight plugin. Here is the error code I get when launching homebridge:

`Unhandled rejection Error: no response timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:125:26)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
`

I tried restarting all my milight bridges and receivers but that did nothing. Hopefully somebody has a solution. 

Thanks

**Comment by tystik4056** [comment]
I just figured it out. I had an unknown power outage at my house that changed the ip address of my wifi box when the router restarted. I just had to update that ip address change in my .json
