### ISSUE TITLE
Unhandled rejection Error: no response timeout

### ISSUE THREAD

**Issue by wadechat** [dotsam/homebridge-milight#49]
I found this code after I done every thing and the homebridge isnt appear in my home app 
any idea about this issue
Thanks,

`Unhandled rejection Error: no response timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:125:26)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)`

**Comment by dotsam** [comment]
Make sure you have the right IP address for your bridge set in your config. Also try installing the latest version as I've updated the node-milight-promise dependancy and I believe it has slightly tweaked error handling for v6 communication timeouts now.

**Comment by Tamas92** [comment]
I have the same issue:

Unhandled rejection Error: no response timeout
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:128:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

Is there any solution for that?

**Comment by pauleec** [comment]
I just moved my hub back to a wired ethernet connection and added a 5th zone of lights to my mi-light hub and am now seeing really bad stability issues causing my whole homebridge mi-lights to completely stop working, requiring a homebridge restart to fix. When I look at the logs I see lots of the following error:
Unhandled rejection Error: no response timeout
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:128:26)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
Up to now with a wifi connection and 4 zones everything has been okay but now I have a wired/ethernet connection and 5 zones.... the whole setup stops working. Please can you advise what is causing the plugin to stop working and let me know what I should do to continue with 5 zones and wired connection. This setup has worked fine for many years... something to do with 5 zones and a wired network seems to have broken its stability. What should I do?
