### ISSUE TITLE
Time out Error - need help!

### ISSUE THREAD

**Issue by turbidWaters** [dotsam/homebridge-milight#56]
I have an automation configured in HomeKit that turns on a milight bulb (fullcolor) on a 8 zone bridge (v6).

The automation is trigerred by a motion sensor. Though the motion sensor always triggers correctly the bulb doesn't turn on at times. On seeing the logs I found that a timeout occours when the automation fails to trigger the bulb to ON. However, if at that same moment if I give a command thru siri or the home app the bulb immediately responds. Here are the logs:

Aug 02 11:10:31 HomeKitBridge homebridge[3941]: [8/2/2018, 11:10:31 AM] [Lights] [Bathroom 2] Setting power state to off
Aug 02 12:58:39 HomeKitBridge homebridge[3941]: Unhandled rejection Error: no response timeout
Aug 02 12:58:39 HomeKitBridge homebridge[3941]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:128:26)
Aug 02 12:58:39 HomeKitBridge homebridge[3941]:     at ontimeout (timers.js:427:11)
Aug 02 12:58:39 HomeKitBridge homebridge[3941]:     at tryOnTimeout (timers.js:289:5)
Aug 02 12:58:39 HomeKitBridge homebridge[3941]:     at listOnTimeout (timers.js:252:5)
Aug 02 12:58:39 HomeKitBridge homebridge[3941]:     at Timer.processTimers (timers.js:212:10)
Aug 02 13:08:09 HomeKitBridge homebridge[3941]: Unhandled rejection Error: no response timeout
Aug 02 13:08:09 HomeKitBridge homebridge[3941]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-milight/node_modules/node-milight-promise/src/milight-v6-mixin.js:128:26)

What am I missing? Is this because the milight bridge's wifi is in sleepmode at the time of the automation being triggered? I am unsure as to how to set the wifi sleep mode to off in the milight bridge.

**Comment by turbidWaters** [comment]
This issue resolved by itself, I dont get any timeout errors anymore!
