### ISSUE TITLE
New series controllers (YL5 and others)

### ISSUE THREAD

**Issue by djsomi** [dotsam/homebridge-milight#60]
Hi Guys,

I've just purchased a new wifi controller, like this:

https://www.futlight.com/productdetails.aspx?id=343&typeid=100

Is it supported by the plugin? With V6 it was not working.

Many Thanks!

**Comment by Tazintosh** [comment]
Bumping this.
I just bought an YL5 and cannot manage to get it work with Homebridge.
Web UI cannot be accessed either because of browser sandboxing: "Sandboxing 'http://XXX.XXX.XXX.XXX/' because it is using HTTP/0.9"

Does anyone have been able to directly use it with Homebridge?

**Comment by djsomi** [comment]
Any news on this Guys?

**Comment by djsomi** [comment]
Hey guys, did you manage to find anything about these controllers? Would be nice to implement into homebridge.

Thanks!

**Comment by ddnl** [comment]
Hi,
i also bought the YL5 but it#s not working.
Any Updates planned regarding the YL5?

BR

**Comment by normen** [comment]
Guys, don't buy the overpriced MiLight boxes, just build a Milight-Hub which can control 200,000 lamps instead of 8 or 4 :)

https://github.com/sidoh/esp8266_milight_hub

**Comment by douginoz** [comment]
Same problem with the YL5 replacement, the WL5.

**Comment by 1aranzant** [comment]
I can get my WL5 partly to work with homebridge when I add it on the Tuya smart app (and tuya homebridge plugin).
But it gives the following error: 
`[TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:227:39)
    at LightAccessory.updateAccessory (/usr/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:14)
    at /usr/lib/node_modules/homebridge-tuya-web/index.js:96:52
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

So the colors don't work properly.
The weird thing is that it works perfectly with google home (via Tuya)
