### ISSUE TITLE
Update 0.4.50 to 0.4.52 -> Error, HB no longer start

### ISSUE THREAD

**Issue by matthias-zivim** [dotsam/homebridge-milight#67]
With the update to v0.4.52 the following message appears

Node.js Version v12.14.1
Npm Version v6.13.6

[3/2/2020, 6:24:55 AM] Error: The requested platform 'MiLight' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

**Comment by marcoschmidt79** [comment]
same problem

Node 13.9.0
NPM 6.13.7

`Mär 02 16:41:10 homebridge homebridge[13223]: [2.3.2020, 16:41:10] Error: The requested platform 'MiLight' was not registered by any plugin.
Mär 02 16:41:10 homebridge homebridge[13223]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Mär 02 16:41:10 homebridge homebridge[13223]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Module._compile (internal/modules/cjs/loader.js:1151:30)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Mär 02 16:41:10 homebridge homebridge[13223]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)`

**Comment by matthias-zivim** [comment]
I have not been able to get another MiLight plugin to work. I have an iBox2

**Comment by dotsam** [comment]
There's a fix in #68 from @fkistner that I'll try and get in to a new release either today or tomorrow.

**Comment by marcoschmidt79** [comment]
> There's a fix in #68 from @fkistner that I'll try and get in to a new release either today or tomorrow.

Thank you so much.

**Comment by shinzan111** [comment]
Yes, same issue here.  After Update Homebridge update Milight plugin doesn't work anymore. Could that please be fixed? Would be really helpful.
thx

**Comment by dotsam** [comment]
Version 1.1.5 should be published now which fixes loading with Homebridge 0.4.52 and higher.
